

SELECT 
IDUSUARIO::VARCHAR(256) ID_USUARIO,
DISPOSITIVO::VARCHAR(256) NOMBRE_DISPOSITIVO,
NUMSERIEDISPOSITIVO::VARCHAR(256) NUMERO_DE_SERIE_DISPOSITIVO,
RESULTADO_MG_POR_DL::number RESULTADO_GLUCOSA_MG_POR_DL,
MINUTOSCOMIDA_LECTURA::NUMBER MINUTOS_ENTRE_COMIDA_Y_MEDIDA,
CARBOHIDRATOSGRAMOS::NUMBER GRAMOS_DE_CARBOHIDRATOS,
TIPOLENTAINS::VARCHAR(256) TipoInsulinaLenta,
UNIDLENTAINS::VARCHAR(256) UNIDADES_INSULINA_LENTA,
COMENTARIO::VARCHAR(400) COMENTARIO,
TIPODEPORTE::VARCHAR(256) TIPO_DEPORTE,
INTENSIDADDEPORTE::VARCHAR(256) INTENSIDAD_DEPORTE,
DURACIONDEPORTE::NUMBER DURACION_DEPORTE,
MINUTOSDEPORTE_LECTURA::NUMBER MINUTOS_ENTRE_DEPORTE_Y_LECTURA,
to_date(substring(sellodeltiempo,2,charindex(' ',sellodeltiempo)-2)) Fecha,
to_time((((SUBSTRING(sellodeltiempo,13,2)::number)*3600 +(SUBSTRING(sellodeltiempo,16,2)::number)*60)::varchar)) HoraMinuto
FROM DEV_BRONZE_DIABETES.PRINCIPAL_SRC.DIABETES_PRINCIPAL_SRC